<?php
use Illuminate\Database\Seeder;
use App\User;

class GroupsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('groups')->insert([
            [
                'id' => 1,
                'faculty_id' => 1,
                'study_program_id' => 1,
                'study_orientation_id' => 1,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 1,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 2,
                'faculty_id' => 1,
                'study_program_id' => 1,
                'study_orientation_id' => 1,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 1,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 3,
                'faculty_id' => 1,
                'study_program_id' => 1,
                'study_orientation_id' => 1,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 2,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 4,
                'faculty_id' => 1,
                'study_program_id' => 1,
                'study_orientation_id' => 1,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 2,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 5,
                'faculty_id' => 1,
                'study_program_id' => 1,
                'study_orientation_id' => 1,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 3,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 6,
                'faculty_id' => 1,
                'study_program_id' => 1,
                'study_orientation_id' => 1,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 3,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 7,
                'faculty_id' => 1,
                'study_program_id' => 1,
                'study_orientation_id' => 1,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 4,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 8,
                'faculty_id' => 1,
                'study_program_id' => 1,
                'study_orientation_id' => 1,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 4,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 9,
                'faculty_id' => 1,
                'study_program_id' => 2,
                'study_orientation_id' => 2,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 1,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 10,
                'faculty_id' => 1,
                'study_program_id' => 2,
                'study_orientation_id' => 2,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 1,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 11,
                'faculty_id' => 1,
                'study_program_id' => 2,
                'study_orientation_id' => 2,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 2,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 12,
                'faculty_id' => 1,
                'study_program_id' => 2,
                'study_orientation_id' => 2,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 2,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 13,
                'faculty_id' => 1,
                'study_program_id' => 2,
                'study_orientation_id' => 2,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 3,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 14,
                'faculty_id' => 1,
                'study_program_id' => 2,
                'study_orientation_id' => 2,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 3,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 15,
                'faculty_id' => 1,
                'study_program_id' => 2,
                'study_orientation_id' => 2,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 4,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 16,
                'faculty_id' => 1,
                'study_program_id' => 2,
                'study_orientation_id' => 2,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 4,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 17,
                'faculty_id' => 1,
                'study_program_id' => 3,
                'study_orientation_id' => 3,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 1,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 18,
                'faculty_id' => 1,
                'study_program_id' => 3,
                'study_orientation_id' => 3,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 1,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 19,
                'faculty_id' => 1,
                'study_program_id' => 3,
                'study_orientation_id' => 3,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 2,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 20,
                'faculty_id' => 1,
                'study_program_id' => 3,
                'study_orientation_id' => 3,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 2,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 21,
                'faculty_id' => 1,
                'study_program_id' => 3,
                'study_orientation_id' => 3,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 3,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 22,
                'faculty_id' => 1,
                'study_program_id' => 3,
                'study_orientation_id' => 3,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 3,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 23,
                'faculty_id' => 1,
                'study_program_id' => 3,
                'study_orientation_id' => 3,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 4,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 24,
                'faculty_id' => 1,
                'study_program_id' => 3,
                'study_orientation_id' => 3,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 4,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 25,
                'faculty_id' => 2,
                'study_program_id' => 4,
                'study_orientation_id' => 4,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 1,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 26,
                'faculty_id' => 2,
                'study_program_id' => 4,
                'study_orientation_id' => 4,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 1,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 27,
                'faculty_id' => 2,
                'study_program_id' => 4,
                'study_orientation_id' => 4,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 2,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 28,
                'faculty_id' => 2,
                'study_program_id' => 4,
                'study_orientation_id' => 4,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 2,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 29,
                'faculty_id' => 2,
                'study_program_id' => 4,
                'study_orientation_id' => 4,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 3,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 30,
                'faculty_id' => 2,
                'study_program_id' => 4,
                'study_orientation_id' => 4,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 3,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 31,
                'faculty_id' => 2,
                'study_program_id' => 4,
                'study_orientation_id' => 4,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 4,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 32,
                'faculty_id' => 2,
                'study_program_id' => 4,
                'study_orientation_id' => 4,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 4,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 33,
                'faculty_id' => 2,
                'study_program_id' => 5,
                'study_orientation_id' => 5,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 1,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 34,
                'faculty_id' => 2,
                'study_program_id' => 5,
                'study_orientation_id' => 5,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 1,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 35,
                'faculty_id' => 2,
                'study_program_id' => 5,
                'study_orientation_id' => 5,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 2,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 36,
                'faculty_id' => 2,
                'study_program_id' => 5,
                'study_orientation_id' => 5,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 2,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 37,
                'faculty_id' => 2,
                'study_program_id' => 5,
                'study_orientation_id' => 5,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 3,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 38,
                'faculty_id' => 2,
                'study_program_id' => 5,
                'study_orientation_id' => 5,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 3,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 39,
                'faculty_id' => 2,
                'study_program_id' => 5,
                'study_orientation_id' => 5,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 4,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 40,
                'faculty_id' => 2,
                'study_program_id' => 5,
                'study_orientation_id' => 5,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 4,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 41,
                'faculty_id' => 2,
                'study_program_id' => 6,
                'study_orientation_id' => 6,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 1,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 42,
                'faculty_id' => 2,
                'study_program_id' => 6,
                'study_orientation_id' => 6,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 1,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 43,
                'faculty_id' => 2,
                'study_program_id' => 6,
                'study_orientation_id' => 6,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 2,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 44,
                'faculty_id' => 2,
                'study_program_id' => 6,
                'study_orientation_id' => 6,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 2,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 45,
                'faculty_id' => 2,
                'study_program_id' => 6,
                'study_orientation_id' => 6,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 3,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 46,
                'faculty_id' => 2,
                'study_program_id' => 6,
                'study_orientation_id' => 6,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 3,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 47,
                'faculty_id' => 2,
                'study_program_id' => 6,
                'study_orientation_id' => 6,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 4,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 48,
                'faculty_id' => 2,
                'study_program_id' => 6,
                'study_orientation_id' => 6,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 4,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 49,
                'faculty_id' => 3,
                'study_program_id' => 7,
                'study_orientation_id' => 7,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 1,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 50,
                'faculty_id' => 3,
                'study_program_id' => 7,
                'study_orientation_id' => 7,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 1,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 51,
                'faculty_id' => 3,
                'study_program_id' => 7,
                'study_orientation_id' => 7,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 2,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 52,
                'faculty_id' => 3,
                'study_program_id' => 7,
                'study_orientation_id' => 7,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 2,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 53,
                'faculty_id' => 3,
                'study_program_id' => 7,
                'study_orientation_id' => 7,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 3,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 54,
                'faculty_id' => 3,
                'study_program_id' => 7,
                'study_orientation_id' => 7,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 3,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 55,
                'faculty_id' => 3,
                'study_program_id' => 7,
                'study_orientation_id' => 7,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 4,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 56,
                'faculty_id' => 3,
                'study_program_id' => 7,
                'study_orientation_id' => 7,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 4,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 57,
                'faculty_id' => 3,
                'study_program_id' => 7,
                'study_orientation_id' => 8,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 1,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 58,
                'faculty_id' => 3,
                'study_program_id' => 7,
                'study_orientation_id' => 8,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 1,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 59,
                'faculty_id' => 3,
                'study_program_id' => 7,
                'study_orientation_id' => 8,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 2,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 60,
                'faculty_id' => 3,
                'study_program_id' => 7,
                'study_orientation_id' => 8,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 2,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 61,
                'faculty_id' => 3,
                'study_program_id' => 7,
                'study_orientation_id' => 8,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 3,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 62,
                'faculty_id' => 3,
                'study_program_id' => 7,
                'study_orientation_id' => 8,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 3,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 63,
                'faculty_id' => 3,
                'study_program_id' => 7,
                'study_orientation_id' => 8,
                'study_degree_id' => 1,
                'study_form_id' => 1,
                'course_id' => 4,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],
            [
                'id' => 64,
                'faculty_id' => 3,
                'study_program_id' => 7,
                'study_orientation_id' => 8,
                'study_degree_id' => 1,
                'study_form_id' => 2,
                'course_id' => 4,
                'size' => 15,
                'created_at' => '2022-08-22 00:00:00',
                'updated_at' => '2022-08-22 00:00:00',
            ],

        ]);
    }
}
